import { Connection, Destination, Source, TransformData } from "src/apis";
import { extractConnectorType } from "@utils/helpers";

const SENSITIVE_KEY_PATTERN = /password|secret|credential|token|\.key$/i;

/** Replaces runs of whitespace with underscores so the name is safe as a .properties key segment. */
function toSafeKey(name: string): string {
  return name.trim().replace(/\s+/g, "_");
}

function redactIfSensitive(key: string, value: string): string {
  return SENSITIVE_KEY_PATTERN.test(key) ? "<REDACTED>" : value;
}

function buildSection(
  entries: Array<[string, string]>,
  comment?: string,
): string[] {
  const lines: string[] =comment ?  [`# ${comment}`] : [];
  for (const [key, value] of entries) {
    lines.push(`${key}=${redactIfSensitive(key, value)}`);
  }
  return lines;
}

/**
 * Generates the content of an application.properties file for Debezium Server
 * Connection config is merged under the source/sink prefix 
 */
export function generatePropertiesContent(
  pipelineName: string,
  source: Source,
  sourceConnection: Connection | null,
  destination: Destination,
  destConnection: Connection | null,
  transforms: TransformData[]
): string {
  const now = new Date().toISOString();
  const header = [
    `# Generated by Debezium Platform`,
    `# Pipeline: ${pipelineName}`,
    `# Generated: ${now}`,
    `# To run: debezium-server --conf application.properties`,
  ];

  const sinkType = extractConnectorType(destination.type);
  const sinkEntries: Array<[string, string]> = [];
  sinkEntries.push(["debezium.sink.type", sinkType]);

  if (destConnection) {
    for (const [k, v] of Object.entries(destConnection.config)) {
      const key = k.startsWith(`${sinkType}.`) ? k : `${sinkType}.${k}`;
      sinkEntries.push([`debezium.sink.${key}`, String(v)]);
    }
  }
  for (const [k, v] of Object.entries(destination.config)) {
    const key = k.startsWith(`${sinkType}.`) ? k : `${sinkType}.${k}`;
    sinkEntries.push([`debezium.sink.${key}`, String(v)]);
  }

  const sourceEntries: Array<[string, string]> = [];
  sourceEntries.push([
    "debezium.source.connector.class",
    source.type,
  ]);

  if (sourceConnection) {
    for (const [k, v] of Object.entries(sourceConnection.config)) {
      sourceEntries.push([`debezium.source.${k}`, String(v)]);
    }
  }
  for (const [k, v] of Object.entries(source.config)) {
    sourceEntries.push([`debezium.source.${k}`, String(v)]);
  }

  const transformLines: string[] = [];
  const predicateLines: string[] = [];

  if (transforms.length > 0) {
    transformLines.push(
      `debezium.transforms=${transforms.map((t) => toSafeKey(t.name)).join(",")}`
    );

    const predicateNames: string[] = [];

    for (const t of transforms) {
      const safeKey = toSafeKey(t.name);
      transformLines.push(`debezium.transforms.${safeKey}.type=${t.type}`);
      for (const [k, v] of Object.entries(t.config)) {
        transformLines.push(
          `debezium.transforms.${safeKey}.${k}=${redactIfSensitive(k, String(v))}`
        );
      }
      if (t.predicate) {
        const predicateName = `${safeKey}Predicate`;
        predicateNames.push(predicateName);
        transformLines.push(
          `debezium.transforms.${safeKey}.predicate=${predicateName}`
        );
        if (t.predicate.negate !== undefined) {
          transformLines.push(
            `debezium.transforms.${safeKey}.negate=${t.predicate.negate}`
          );
        }
      }
    }

    if (predicateNames.length > 0) {
      predicateLines.push(
        `debezium.predicates=${predicateNames.join(",")}`
      );
      for (const t of transforms) {
        if (!t.predicate) continue;
        const predicateName = `${toSafeKey(t.name)}Predicate`;
        predicateLines.push(
          `debezium.predicates.${predicateName}.type=${t.predicate.type}`
        );
        for (const [k, v] of Object.entries(t.predicate.config ?? {})) {
          predicateLines.push(
            `debezium.predicates.${predicateName}.${k}=${redactIfSensitive(k, String(v))}`
          );
        }
      }
    }
  }

  // ── Runtime stub ───────────────────────────────────────────────────────────
  // const runtimeStub = [
  //   `# ── Runtime properties (fill in before running) ${"─".repeat(16)}`,
  //   `# debezium.source.offset.storage.file.filename=data/offsets.dat`,
  //   `# debezium.source.offset.flush.interval.ms=0`,
  // ];

  const sinkSection = buildSection(
    sinkEntries
  );
  const sourceSection = buildSection(
    sourceEntries,
        // `── Source (Connector) ${"─".repeat(51)}`,
  );

  const parts: string[][] = [
    header,
    [""],
    sinkSection,
    sourceSection,
  ];

  if (transformLines.length > 0) {
    parts.push(transformLines);
  }
  if (predicateLines.length > 0) {
    parts.push(predicateLines);
  }
  // For now
  // parts.push(runtimeStub);

  return parts.map((section) => section.join("\n")).join("\n");
}

/**
 * Triggers a browser download of the given text content as a .properties file.
 */
export function triggerPropertiesDownload(
  filename: string,
  content: string
): void {
  const blob = new Blob([content], { type: "text/plain" });
  const url = window.URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  window.URL.revokeObjectURL(url);
  document.body.removeChild(a);
}
